cinemas/models.py
from app import db


class Customer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    iso = db.Column(db.String(2))
    name = db.Column(db.String(20))

    def __init__(self, *args, **kwargs):
        super(Customer, self).__init__(*args, **kwargs)

    def __repr__(self):
        return f'<Customer {self.id} - {self.name} [{self.iso}]>'

cinemas/app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy



app = Flask(__name__)

app.config.from_object(Configuration)
db = SQLAlchemy(app)

cinemas/cinemas/blueprint.py
from flask import Blueprint, render_template
from models import Customer

cinemas = Blueprint('cinemas', __name__, template_folder='templates')

@cinemas.route('/customers')
def index():
    customers = Customer.query.all()
    return render_template('cinemas/index.html', customers=customers)

@cinemas.route('customers/<iso>/<name>')
def customer_detail(iso, name):
    customer = Customer.query.filter(Customer.iso==iso, Customer.name==name).first()
    return render_template('cinemas/customer_info.html', customer=customer)

cinemas/main.py
from app import app
from cinemas.blueprint import cinemas
import view

app.register_blueprint(cinemas, url_prefix='/stereolife')



if __name__ == '__main__':
    app.run()

cinemas/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TVR</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
        <a class="navbar-brand" href="{{ url_for('index') }}">Stereolife</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">Product types</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('cinemas.index') }}">Client base</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#"><small>add-object</small></a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="#">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            <a class="btn btn-light" href="/admin">Admin</a>
        </div>
    </nav>

    {% block breadcrumb %}{% endblock %}

    {% block content %}{% endblock %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

cinemas/templates/index.html
{% extends 'base.html' %}

  {% block breadcrumb %}{% endblock %}

  {% block content %}
    <h1 style="color: MediumSeaGreen; text-align:center; margin-top:20px;">WTF Stereolife</h1>

    <iframe width="560" height="315" src="https://www.youtube.com/embed/meBGuFs9N6w" frameborder="0"
            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen
            style="display: block; margin: 0 auto; margin-top: 50px;">
    </iframe>
  {% endblock %}